backend:
  name: github
  repo: createno1234/clayjars-church
  branch: main
  base_url: https://clayjars-church.kr
  auth_endpoint: ""

media_folder: "gallery"
public_folder: "gallery"

collections:
  - name: "gallery"
    label: "교회 앨범 사진"
    folder: "content/gallery"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "앨범 제목", name: "title", widget: "string" }
      - label: "카테고리 분류"
        name: "category"
        widget: "select"
        options: ["행사/친교", "주일예배", "선교", "빚음부(교회학교)"]
        default: "선교"
      - { label: "촬영 일자", name: "date", widget: "datetime", format: "YYYY-MM-DD", dateFormat: "YYYY-MM-DD", timeFormat: false }
      - label: "앨범 사진 등록 (여러 장 추가)"
        name: "photos"
        widget: "list"
        summary: "{{fields.photo}}"
        field: { label: "사진 선택", name: "photo", widget: "image", choose_url: false }
      - { label: "간단한 설명", name: "description", widget: "text", required: false }
